apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: rulezilla
  description:  Rule DSL
  annotations:
    backstage.io/techdocs-ref: dir:. 
spec:
  type: library
  lifecycle: production
