
name: "Dobby action"
on:
  issue_comment:
    types: [created]
permissions:
  contents: read
jobs:
  pr_commented:
    uses: simplybusiness/github-action-reusable-workflows/.github/workflows/dobby.yaml@v1
    with:
      version_file_path: ./lib/rulezilla/version.rb
    secrets: inherit