name: Master Build

on:
  push:
    branches:
      - 'master'

env:
  REPOSITORY: "rulezilla"

concurrency: huxley-ci-${{ github.ref }}

jobs:
  CheckAndBuildGem:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id    : ${{ secrets.AWS_LIVE_CICD_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_LIVE_CICD_SECRET_ACCESS_KEY }}
          aws-region           : ${{ secrets.AWS_LIVE_CICD_REGION }}
      - name: Check Semaphore and Build Gem
        uses: aws-actions/aws-codebuild-run-build@v1
        with:
          project-name: ${{ env.REPOSITORY }}
          buildspec-override: _pipeline/stage_check_and_build_gem.yml

  Notify:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id    : ${{ secrets.AWS_LIVE_CICD_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_LIVE_CICD_SECRET_ACCESS_KEY }}
          aws-region           : ${{ secrets.AWS_LIVE_CICD_REGION }}
      - name: Slack Notification
        uses: aws-actions/aws-codebuild-run-build@v1
        with:
          project-name: ${{ env.REPOSITORY }}
          buildspec-override: _pipeline/stage_notify.yml
